modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Jozufozu/Yoyos/issues"
[[mods]]
modId="yoyos"
version="${file.jarVersion}"
logoFile="icon.png"
displayName="Yoyos"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yoyos"
credits="Terraria, for having sweet yoyos that I wanted to make in Minecraft"
authors="Jozufozu"
description='''
Childerens' toy based weaponry! Adds yoyos that can attack, garden, farm, and act as grappling hooks.'''
[[dependencies.yoyos]]
    modId="jei"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"